# This is a basic workflow to help you get started with Actions
name: "build-test"
on: 
  [push]

jobs:
  test_something:
    runs-on: ubuntu-latest
    #env:
      #working-directory: ../../sandipghosh84-5-DEV-SFDC-Project/src/pages/
    # Runs a single command using the runners shell
    steps:
    - run: | 
        echo $GITHUB_REPOSITORY
        cd $GITHUB_REPOSITORY
        ls -la
        echo $GITHUB_WORKSPACE
        cd ${{github.workspace}}
        echo -current path--
        pwd
        ls -lrt
    - uses: actions/checkout@v1
    - uses: LouisBrunner/diff-action@v0.1.0
      #find current working directory
      with:
        old: helloWorld.page
        new: helloWorld_1.page
        mode: addition
        tolerance: mixed
        output: out.txt
