# This is a basic workflow to help you get started with Actions
name: "build-test"
on: 
  [push]

jobs:
  test_something:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: LouisBrunner/diff-action@v0.1.0
      with:
        old: sandipghosh84Plus5-devSFDC/sandipghosh84-5-DEV-SFDC-Project/src/pages/helloWorld.page
        new: sandipghosh84Plus5-devSFDC/sandipghosh84-5-DEV-SFDC-Project/src/pages/helloWorld_1.page
        mode: addition
        tolerance: mixed
        output: sandipghosh84Plus5-devSFDC/sandipghosh84-5-DEV-SFDC-Project/src/pages/out.txt
